SlackNotificationsJobSettings:
    LogsConnectionString:
        settings-key: SlackNotificationsJobSettings-LogsConnectionString
        types:
        - AzureTableStorage
    SharedStorageConnString:
        settings-key: SlackNotificationsJobSettings-SharedStorageConnString
        types:
        - AzureTableStorage
    FullMessagesConnString:
        settings-key: SlackNotificationsJobSettings-FullMessagesConnString
        types:
        - AzureTableStorage
    MutedSenders:
        settings-key: SlackNotificationsJobSettings-MutedSenders
        types:
        - Optional
        - Json
    MutedMessagePrefixes:
        settings-key: SlackNotificationsJobSettings-MutedMessagePrefixes
        types:
        - Optional
        - Json
    MutedRegexMessage:
        settings-key: SlackNotificationsJobSettings-MutedRegexMessage
        types:
        - Optional
        - Json
SlackIntegration:
    Env:
        settings-key: SlackIntegration-Env
    Channels:
        settings-key: SlackIntegration-Channels
        types:
            - JsonArray
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
